import { createThemePreferenceFromVsCodeTheme } from "@pstdio/ui";

const theme = (id: string, mode: "light" | "dark", colors: Record<string, string>) =>
  createThemePreferenceFromVsCodeTheme({ id, mode, theme: { colors } });

export const scribbleTheme = theme("showcase.scribble", "light", {
  "editor.background": "#fbf8f2",
  "editor.foreground": "#332f2a",
  "editorWidget.background": "#fffdf8",
  "activityBar.background": "#eee7db",
  "sideBar.background": "#f2ede3",
  "panel.background": "#fffdf8",
  "statusBar.background": "#eee7db",
  "input.background": "#e9e2d6",
  "input.foreground": "#332f2a",
  "input.border": "#d8cfbf",
  "menu.background": "#fffdf8",
  "menu.foreground": "#332f2a",
  "menu.selectionBackground": "#e9e2d6",
  "list.hoverBackground": "#e9e2d6",
  "list.activeSelectionBackground": "#dfd5c5",
  "button.background": "#b85c38",
  "button.hoverBackground": "#98492c",
  "button.foreground": "#ffffff",
  "badge.background": "#e8ddcf",
  "badge.foreground": "#66594b",
  focusBorder: "#b85c38",
  foreground: "#332f2a",
  descriptionForeground: "#746b61",
  disabledForeground: "#aaa095",
  border: "#ded6ca",
});

export const boomboxTheme = theme("showcase.boombox", "dark", {
  "editor.background": "#0d0f0e",
  "editor.foreground": "#f5f7f5",
  "editorWidget.background": "#171a18",
  "activityBar.background": "#090b0a",
  "sideBar.background": "#111412",
  "panel.background": "#171a18",
  "statusBar.background": "#090b0a",
  "input.background": "#242825",
  "input.foreground": "#f5f7f5",
  "input.border": "#343a35",
  "menu.background": "#171a18",
  "menu.foreground": "#f5f7f5",
  "menu.selectionBackground": "#283029",
  "list.hoverBackground": "#222824",
  "list.activeSelectionBackground": "#2c382f",
  "button.background": "#4dd879",
  "button.hoverBackground": "#70e18f",
  "button.foreground": "#07130a",
  "badge.background": "#253329",
  "badge.foreground": "#8be6a6",
  focusBorder: "#4dd879",
  foreground: "#f5f7f5",
  descriptionForeground: "#a2aaa4",
  disabledForeground: "#656c67",
  border: "#292e2a",
});

export const ziplineTheme = theme("showcase.zipline", "dark", {
  "editor.background": "#11101a",
  "editor.foreground": "#f3f1ff",
  "editorWidget.background": "#181625",
  "activityBar.background": "#0c0b13",
  "sideBar.background": "#151321",
  "panel.background": "#181625",
  "statusBar.background": "#0c0b13",
  "input.background": "#242136",
  "input.foreground": "#f3f1ff",
  "input.border": "#353149",
  "menu.background": "#181625",
  "menu.foreground": "#f3f1ff",
  "menu.selectionBackground": "#2a2640",
  "list.hoverBackground": "#211e31",
  "list.activeSelectionBackground": "#2f294a",
  "button.background": "#7867e6",
  "button.hoverBackground": "#9284ed",
  "button.foreground": "#ffffff",
  "badge.background": "#292440",
  "badge.foreground": "#c6bcff",
  focusBorder: "#8f7df0",
  foreground: "#f3f1ff",
  descriptionForeground: "#aaa5c2",
  disabledForeground: "#67627b",
  border: "#302d40",
});

export const pigeonTheme = theme("showcase.pigeon", "light", {
  "editor.background": "#f8fbff",
  "editor.foreground": "#202632",
  "editorWidget.background": "#ffffff",
  "activityBar.background": "#e7f0fc",
  "sideBar.background": "#eef5ff",
  "panel.background": "#ffffff",
  "statusBar.background": "#e7f0fc",
  "input.background": "#e4edf9",
  "input.foreground": "#202632",
  "input.border": "#cbd8e8",
  "menu.background": "#ffffff",
  "menu.foreground": "#202632",
  "menu.selectionBackground": "#dfeafe",
  "list.hoverBackground": "#edf4ff",
  "list.activeSelectionBackground": "#dbe8fb",
  "button.background": "#356fd1",
  "button.hoverBackground": "#285db8",
  "button.foreground": "#ffffff",
  "badge.background": "#dfeafe",
  "badge.foreground": "#315f9d",
  focusBorder: "#356fd1",
  foreground: "#202632",
  descriptionForeground: "#687486",
  disabledForeground: "#9ca8b7",
  border: "#d7e0ec",
});

export const kilnTheme = theme("showcase.kiln", "dark", {
  "editor.background": "#25272b",
  "editor.foreground": "#e7e9ec",
  "editorWidget.background": "#303237",
  "activityBar.background": "#1b1d20",
  "sideBar.background": "#292b2f",
  "panel.background": "#2c2e32",
  "statusBar.background": "#1b1d20",
  "input.background": "#202226",
  "input.foreground": "#e7e9ec",
  "input.border": "#45484e",
  "menu.background": "#303237",
  "menu.foreground": "#e7e9ec",
  "menu.selectionBackground": "#494c52",
  "list.hoverBackground": "#383a3f",
  "list.activeSelectionBackground": "#4b4135",
  "button.background": "#e98732",
  "button.hoverBackground": "#f29a4d",
  "button.foreground": "#1d130b",
  "badge.background": "#4b4135",
  "badge.foreground": "#ffc58c",
  focusBorder: "#f29a4d",
  foreground: "#e7e9ec",
  descriptionForeground: "#aeb2b8",
  disabledForeground: "#6f7379",
  border: "#42454a",
});
