import type { BoundaryConfig, DeniedContent } from "./boundary-verifier";

const DOMAIN_DENIED_CONTENT: DeniedContent[] = [
  { label: "ticket", pattern: /\btickets?\b/i },
  { label: "tag", pattern: /\btags?\b/i },
  { label: "status", pattern: /\bstatuses?\b/i },
  { label: "template", pattern: /\btemplates?\b/i },
];

const WORKBENCH_CORE_DOMAIN_ALLOWLIST = [
  "packages/pstdio-workbench/src/core/controllers/history/history-controller.test.ts",
  "packages/pstdio-workbench/src/core/controllers/last-resource/last-resource-controller.test.ts",
  "packages/pstdio-workbench/src/core/registries/commands/command-registry.test.ts",
  "packages/pstdio-workbench/src/core/registries/layout/layout-model-placement.test.ts",
  "packages/pstdio-workbench/src/core/registries/layout/layout-model.test.ts",
  "packages/pstdio-workbench/src/core/registries/layout/surface-reconcile.test.ts",
  "packages/pstdio-workbench/src/core/registries/navigation/navigation-registry.test.ts",
  "packages/pstdio-workbench/src/core/registries/renderers/data-renderer-registry.test.ts",
  "packages/pstdio-workbench/src/core/registries/renderers/tree-renderer-registry.test.ts",
  "packages/pstdio-workbench/src/core/registries/renderers/tree-renderer-registry.ts",
  "packages/pstdio-workbench/src/core/registries/resources/resource-registry.test.ts",
  "packages/pstdio-workbench/src/core/workbench-core.test.ts",
  "packages/pstdio-workbench/src/core/workbench-core.ts",
];

const UI_DOMAIN_ALLOWLIST = [
  "packages/ui/src/components/activity/",
  "packages/ui/src/components/chat-ui/",
  "packages/ui/src/components/checkbox.stories.tsx",
  "packages/ui/src/components/data-renderer/",
  "packages/ui/src/components/header.stories.tsx",
  "packages/ui/src/components/icon-color-picker.tsx",
  "packages/ui/src/components/list-row/",
  "packages/ui/src/components/palette-list.test.tsx",
  "packages/ui/src/components/palette.stories.tsx",
  "packages/ui/src/components/param-editor/",
  "packages/ui/src/components/radio.stories.tsx",
  "packages/ui/src/components/repo-picker-dialog.stories.tsx",
  "packages/ui/src/components/rich-text/",
  "packages/ui/src/components/style-guide-data.ts",
  "packages/ui/src/components/tag-editor/",
  "packages/ui/src/components/tree-list/",
  "packages/ui/src/components/workspace-badge.stories.tsx",
  "packages/ui/src/index.ts",
];

export const DEFAULT_BOUNDARY_CONFIG: BoundaryConfig = {
  allowedWorkspaceDeps: {
    "pstdio-api-contracts": [],
    "pstdio-file-types": [],
    "pstdio-paths": [],
    "pstdio-logging": ["pstdio-paths"],
    "pstdio-db": ["pstdio-paths"],
    "pstdio-scheduler": [],
    "pstdio-wt": ["pstdio-file-types"],
    "pstdio-storage": ["pstdio-api-contracts", "pstdio-db", "pstdio-paths"],
    "@pstdio/sdk": ["pstdio-api-contracts"],
    "pstdio-extensions": ["@pstdio/sdk", "pstdio-api-contracts", "pstdio-paths"],
    "pstdio-api-runtime-host": ["pstdio-api-contracts", "pstdio-extensions"],
    "pstdio-api": [
      "pstdio-api-contracts",
      "pstdio-api-runtime-host",
      "pstdio-db",
      "pstdio-extensions",
      "pstdio-logging",
      "pstdio-paths",
      "pstdio-scheduler",
      "pstdio-storage",
      "pstdio-wt",
    ],
    pstdio: [
      "@pstdio/sdk",
      "pstdio-api",
      "pstdio-api-contracts",
      "pstdio-dashboard",
      "pstdio-db",
      "pstdio-logging",
      "pstdio-paths",
      "pstdio-wt",
    ],
    "@pstdio/ui": ["pstdio-file-types"],
    "pstdio-workbench": ["@pstdio/sdk", "@pstdio/ui", "pstdio-extensions"],
    "pstdio-dashboard": ["@pstdio/sdk", "@pstdio/ui", "pstdio-api-contracts", "pstdio-extensions", "pstdio-workbench"],
    "pstdio-extension-testbench": ["@pstdio/sdk", "@pstdio/ui", "pstdio-extensions", "pstdio-workbench"],
    e2e: ["pstdio", "pstdio-api-contracts", "pstdio-db", "pstdio-extensions", "pstdio-wt"],
    "pstdio-scripts": ["pstdio-extensions"],
    "@pstdio/landing-page": ["@pstdio/ui"],
  },
  contentDenylistRules: [
    {
      deniedContent: DOMAIN_DENIED_CONTENT,
      label: "workbench core domain vocabulary",
      packageName: "pstdio-workbench",
      allowlist: WORKBENCH_CORE_DOMAIN_ALLOWLIST,
      pathPrefixes: ["src/core"],
    },
    {
      deniedContent: DOMAIN_DENIED_CONTENT,
      label: "UI domain vocabulary",
      packageName: "@pstdio/ui",
      allowlist: UI_DOMAIN_ALLOWLIST,
      pathPrefixes: ["src"],
    },
  ],
  extensionAllowedDeps: ["@pstdio/sdk", "@pstdio/ui"],
  extensionLayer: 7,
  forbiddenSpecifiers: {
    "@pstdio/ui": ["@tanstack/react-router", "@tanstack/react-query"],
  },
  fixtureSourceFiles: [
    "packages/e2e/src/packaged/extension-fixtures.ts",
    "packages/pstdio-api/src/features/extensions/install-extension-source-deps.test.ts",
  ],
  packageLayers: {
    "pstdio-api-contracts": 0,
    "pstdio-file-types": 0,
    "pstdio-paths": 0,
    "pstdio-scheduler": 0,
    "pstdio-wt": 1,
    "pstdio-db": 1,
    "pstdio-logging": 1,
    "pstdio-storage": 2,
    "@pstdio/sdk": 3,
    "pstdio-extensions": 4,
    "pstdio-api-runtime-host": 5,
    "pstdio-api": 6,
    "@pstdio/ui": 5,
    "pstdio-workbench": 6,
    "pstdio-dashboard": 8,
    "pstdio-extension-testbench": 8,
    "@pstdio/landing-page": 8,
    pstdio: 9,
    e2e: 10,
    "pstdio-scripts": 10,
  },
  relativeEscapeAllowlist: ["packages/pstdio/src/_embed-manifest.generated.ts"],
  // `node:` is path-scoped because chat-ui/agent-types.ts intentionally models
  // Node stream types while the rest of @pstdio/ui stays browser-safe.
  specifierDenylistRules: [
    {
      forbiddenSpecifiers: ["node:"],
      packageName: "@pstdio/ui",
      allowlist: ["packages/ui/src/components/chat-ui/agent-types.ts"],
      pathPrefixes: ["src"],
    },
    {
      forbiddenSpecifiers: [
        "react",
        "react-dom",
        "@chakra-ui/react",
        "@chakra-ui/charts",
        "@pstdio/ui",
        "pstdio-dashboard",
      ],
      packageName: "pstdio-workbench",
      allowTypeOnlySpecifiers: ["react", "react-dom", "@chakra-ui/react", "@chakra-ui/charts", "pstdio-dashboard"],
      pathPrefixes: ["src/core"],
    },
  ],
};
