UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-status.read' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketStatus.read';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketStatus.read"', '"pstdio.pstdio-planner.command.ticket-status.read"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketStatus.read"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-status.create' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketStatus.create';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketStatus.create"', '"pstdio.pstdio-planner.command.ticket-status.create"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketStatus.create"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-status.update' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketStatus.update';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketStatus.update"', '"pstdio.pstdio-planner.command.ticket-status.update"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketStatus.update"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-status.delete' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketStatus.delete';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketStatus.delete"', '"pstdio.pstdio-planner.command.ticket-status.delete"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketStatus.delete"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-status.set-default' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketStatus.setDefault';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketStatus.setDefault"', '"pstdio.pstdio-planner.command.ticket-status.set-default"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketStatus.setDefault"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-status.reorder' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketStatus.reorder';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketStatus.reorder"', '"pstdio.pstdio-planner.command.ticket-status.reorder"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketStatus.reorder"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.read' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.read';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.read"', '"pstdio.pstdio-planner.command.ticket-tag.read"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.read"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.create' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.create';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.create"', '"pstdio.pstdio-planner.command.ticket-tag.create"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.create"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.update' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.update';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.update"', '"pstdio.pstdio-planner.command.ticket-tag.update"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.update"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.delete' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.delete';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.delete"', '"pstdio.pstdio-planner.command.ticket-tag.delete"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.delete"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.create-option' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.createOption';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.createOption"', '"pstdio.pstdio-planner.command.ticket-tag.create-option"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.createOption"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.update-option' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.updateOption';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.updateOption"', '"pstdio.pstdio-planner.command.ticket-tag.update-option"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.updateOption"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.delete-option' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.deleteOption';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.deleteOption"', '"pstdio.pstdio-planner.command.ticket-tag.delete-option"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.deleteOption"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.ticket-tag.apply-draft' WHERE "command_id" = 'pstdio.pstdio-planner.command.ticketTag.applyDraft';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.ticketTag.applyDraft"', '"pstdio.pstdio-planner.command.ticket-tag.apply-draft"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.ticketTag.applyDraft"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-planner.command.run-review' WHERE "command_id" = 'pstdio.pstdio-planner.command.runReview';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-planner.command.runReview"', '"pstdio.pstdio-planner.command.run-review"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-planner.command.runReview"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-dev.command.issues.discover-high-impact' WHERE "command_id" = 'pstdio.pstdio-dev.command.issues.discoverHighImpact';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-dev.command.issues.discoverHighImpact"', '"pstdio.pstdio-dev.command.issues.discover-high-impact"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-dev.command.issues.discoverHighImpact"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-dev.command.workspace.open-in-vscode' WHERE "command_id" = 'pstdio.pstdio-dev.command.workspace.openInVscode';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-dev.command.workspace.openInVscode"', '"pstdio.pstdio-dev.command.workspace.open-in-vscode"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-dev.command.workspace.openInVscode"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-dev.command.workspace.open-in-isolation' WHERE "command_id" = 'pstdio.pstdio-dev.command.workspace.openInIsolation';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-dev.command.workspace.openInIsolation"', '"pstdio.pstdio-dev.command.workspace.open-in-isolation"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-dev.command.workspace.openInIsolation"%';--> statement-breakpoint
UPDATE "automation_runs" SET "command_id" = 'pstdio.pstdio-dev.command.workspace.stop-isolation' WHERE "command_id" = 'pstdio.pstdio-dev.command.workspace.stopIsolation';--> statement-breakpoint
UPDATE "automation_tokens" SET "command_scopes_json" = replace("command_scopes_json"::text, '"pstdio.pstdio-dev.command.workspace.stopIsolation"', '"pstdio.pstdio-dev.command.workspace.stop-isolation"')::jsonb WHERE "command_scopes_json"::text LIKE '%"pstdio.pstdio-dev.command.workspace.stopIsolation"%';--> statement-breakpoint
UPDATE "extension_automation_preferences" SET "automation_id" = 'pstdio.pstdio-dev.schedule.daily-issue-discovery' WHERE "automation_id" = 'pstdio.pstdio-dev.schedule.dailyIssueDiscovery';--> statement-breakpoint
UPDATE "extension_automation_preferences" SET "automation_id" = 'pstdio.pstdio-planner-loops.schedule.refine-tickets' WHERE "automation_id" = 'pstdio.pstdio-planner-loops.schedule.refineTickets';--> statement-breakpoint
UPDATE "extension_automation_preferences" SET "automation_id" = 'pstdio.pstdio-planner-loops.schedule.implement-tickets' WHERE "automation_id" = 'pstdio.pstdio-planner-loops.schedule.implementTickets';--> statement-breakpoint
UPDATE "extension_automation_preferences" SET "automation_id" = 'pstdio.pstdio-planner-loops.schedule.stuck-work-sweep' WHERE "automation_id" = 'pstdio.pstdio-planner-loops.schedule.stuckWorkSweep';--> statement-breakpoint
UPDATE "extension_automation_preferences" SET "automation_id" = 'pstdio.pstdio-planner-loops.schedule.review-tickets' WHERE "automation_id" = 'pstdio.pstdio-planner-loops.schedule.reviewTickets';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'create-proposal' WHERE "skill_key" = 'create_proposal';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'create-sub-tickets' WHERE "skill_key" = 'create_sub_tickets';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'create-ticket' WHERE "skill_key" = 'create_ticket';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'implement-ticket' WHERE "skill_key" = 'implement_ticket';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'refine-ticket' WHERE "skill_key" = 'refine_ticket';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'use-reports' WHERE "skill_key" = 'use_reports';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'create-pstdio-extension' WHERE "skill_key" = 'create_pstdio_extension';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'lab-resource' WHERE "skill_key" = 'labResource';--> statement-breakpoint
UPDATE "extension_skill_preferences" SET "skill_key" = 'font-editor' WHERE "skill_key" = 'fontEditor';
