export type {
  CreateNotificationInput,
  ListNotificationsQuery,
  ListNotificationsResponse,
  Notification,
  NotificationAction,
  NotificationActionResult,
  NotificationActorType,
  NotificationKind,
  NotificationOrigin,
  NotificationPriority,
  NotificationStatus,
  UpdateNotificationInput,
} from "pstdio-api-contracts";
export type * from "pstdio-api-contracts/extension-kernel";
export type {
  CommitPayload,
  ConflictPayload,
  MergePayload,
  RebasePayload,
  SessionLifecyclePayload,
  WorkspaceProvisionPayload,
  WorkspaceType,
  WorktreeRemovedPayload,
} from "pstdio-api-contracts/extension-kernel";
export {
  ALWAYS_AVAILABLE_WEBVIEW_CAPABILITIES,
  defineSlot,
  dockedWorkbenchRegions,
  EXTENSION_API_VERSION,
  gitEvents,
  isLocalizedString,
  isValidLocalContributionId,
  type Localizable,
  type LocalizedString,
  l10n,
  localContributionIdGrammar,
  localContributionIdPattern,
  packageAsset,
  projectEvents,
  projectSlots,
  sessionEvents,
  sessionSlots,
  WEBVIEW_DECLARABLE_CAPABILITIES,
  WEBVIEW_HOST_CAPABILITIES,
  WEBVIEW_HOST_CAPABILITY_VERSION,
  workbenchCommands,
  workbenchModeDefinitions,
  workbenchModes,
  workbenchPageDefinitions,
  workbenchPages,
  workbenchPanelDefinitions,
  workbenchPanels,
  workbenchResourceKindDefinitions,
  workbenchResourceKinds,
  workbenchSlots,
  workspaceEvents,
  workspaceSlots,
  worktreeEvents,
} from "pstdio-api-contracts/extension-kernel";
export { type CommandResponse, unwrapCommandOutcome } from "./command-outcome";
export { defineCommand, defineHook, defineMiddleware } from "./define-command";
export {
  defineActivityItem,
  defineArtifactMount,
  defineCommandPaletteResource,
  defineConnection,
  defineFileIconTheme,
  defineHarness,
  defineKeybinding,
  defineMode,
  defineNavigationItem,
  definePage,
  definePlacement,
  defineResourceHierarchyProvider,
  defineResourceKind,
  defineResourceView,
  defineSchedule,
  defineSettingsPanel,
  defineSettingsSection,
  defineSkill,
  defineStatusBarItem,
  defineStatuses,
  defineTemplate,
  defineTemplateType,
  defineTheme,
  defineView,
  defineViewMenu,
  defineWorkspaceType,
  resourceMenuSlotRef,
  resourceSlotRef,
} from "./define-contribution";
export { defineExtension } from "./define-extension";
export {
  defineExtensionView,
  type ExtensionViewModule,
  type ExtensionViewRender,
  type ExtensionViewRenderContext,
  type GuestHost,
  type PropsStore,
  type WebviewFilesClient,
} from "./define-extension-view";
export { params } from "./params";
export { commandEvent, commandRef, eventRef } from "./refs";
export {
  createTerminalSessionBridge,
  type TerminalSessionAdapter,
  type TerminalSessionBridge,
  type TerminalSessionExit,
} from "./terminal-session-bridge";
export { type ArtifactMountKey, artifactMountId, artifactsRead } from "./webview-capabilities";
export {
  createWebviewClient,
  type WebviewArtifactsClient,
  type WebviewClient,
  type WebviewClientOptions,
  type WebviewCommandsClient,
  type WebviewSettingsClient,
} from "./webview-client";
export { matchesResourceWhen } from "./when";
