// xterm.js needs concrete color strings, so the terminal palette uses raw tokens
// with one set per preset instead of light/dark semantic tokens. Values stay
// literal because `system.token()` returns a CSS variable for token references.
export const terminal = {
  light: {
    background: { value: "#f4f4f5" },
    foreground: { value: "#171717" },
    cursor: { value: "#171717" },
    cursorAccent: { value: "#000000" },
    selectionBackground: { value: "#d4d4d8" },
    black: { value: "#27272a" },
    red: { value: "#dc2626" },
    green: { value: "#16a34a" },
    yellow: { value: "#ca8a04" },
    blue: { value: "#2563eb" },
    magenta: { value: "#c026d3" },
    cyan: { value: "#0891b2" },
    white: { value: "#e4e4e7" },
    brightBlack: { value: "#52525b" },
    brightRed: { value: "#ef4444" },
    brightGreen: { value: "#22c55e" },
    brightYellow: { value: "#eab308" },
    brightBlue: { value: "#3b82f6" },
    brightMagenta: { value: "#d946ef" },
    brightCyan: { value: "#06b6d4" },
    brightWhite: { value: "#fafafa" },
  },
  dark: {
    background: { value: "#0a0a0a" },
    foreground: { value: "#fafafa" },
    cursor: { value: "#fafafa" },
    cursorAccent: { value: "#000000" },
    selectionBackground: { value: "#3f3f46" },
    black: { value: "#27272a" },
    red: { value: "#f87171" },
    green: { value: "#4ade80" },
    yellow: { value: "#facc15" },
    blue: { value: "#60a5fa" },
    magenta: { value: "#e879f9" },
    cyan: { value: "#22d3ee" },
    white: { value: "#e4e4e7" },
    brightBlack: { value: "#52525b" },
    brightRed: { value: "#fca5a5" },
    brightGreen: { value: "#86efac" },
    brightYellow: { value: "#fde047" },
    brightBlue: { value: "#93c5fd" },
    brightMagenta: { value: "#f0abfc" },
    brightCyan: { value: "#67e8f9" },
    brightWhite: { value: "#fafafa" },
  },
};
