import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const entrypoint = join(import.meta.dirname, "../src/bridge/guest/bootstrap.ts");
const outfile = join(import.meta.dirname, "../src/bridge/webview-runtime/runtime.bundle.js");

const result = await Bun.build({
  entrypoints: [entrypoint],
  format: "esm",
  minify: true,
  sourcemap: "none",
  target: "browser",
});

if (!result.success) {
  for (const log of result.logs) {
    console.error(log);
  }
  process.exit(1);
}

const output = result.outputs.find((item) => item.kind === "entry-point");
if (!output) {
  throw new Error("Runtime bundle was not produced.");
}

const bundledScript = (await output.text()).trimEnd();

mkdirSync(dirname(outfile), { recursive: true });
writeFileSync(outfile, `// Generated by packages/pstdio-extensions/scripts/build-runtime.ts\n${bundledScript}\n`);
