export const remoteWorkspaceCapabilities = {
  files: "none" as const,
  diff: false,
  merge: false,
  rebase: false,
  archive: true,
  delete: true,
};

export const makeWorkspace = (overrides: Record<string, unknown> = {}) => ({
  id: "ws-1",
  project_id: "project-1",
  name: "WS-1",
  branch: null,
  worktree_path: null,
  provider_id: "pocketcoder.remote",
  provider_params_json: { repository: "repo" },
  provider_ref_json: { version: 1, data: { remoteId: "remote-1" } },
  provider_state: "ready" as const,
  execution_kind: "remote" as const,
  provider_operation_id: null,
  provider_operation_kind: null,
  provider_error_json: null,
  provider_capabilities_json: remoteWorkspaceCapabilities,
  display_path: "Pocket Coder remote-1",
  is_default: false,
  archived: false,
  workspace_shorthand: "WS-1",
  initializing: false,
  setup_error: null,
  startup_log_file_id: null,
  anchors_json: [],
  created_at: "2026-08-26T00:00:00.000Z",
  updated_at: "2026-08-26T00:00:00.000Z",
  deleted_at: null,
  ...overrides,
});
