import { defineSlotRecipe } from "@chakra-ui/react";
import { BOARD_SCALE } from "../../services/shapes/assembly-layout";

export const landingSlotRecipe = defineSlotRecipe({
  slots: [
    "root",
    "window",
    "titlebar",
    "windowControls",
    "windowControl",
    "actionMenuButton",
    "mobileTitlebar",
    "sidebar",
    "sidebarScroll",
    "sidebarRows",
    "sidebarHeading",
    "sidebarFooter",
    "status",
    "copyright",
    "releaseBadge",
    "body",
    "main",
    "hero",
    "heroLayout",
    "cardSpace",
    "heroCopy",
    "download",
    "downloadDescription",
    "downloadPlatforms",
    "siteTabs",
    "siteTab",
    "siteTabIcon",
    "siteTabLabel",
  ],
  base: {
    root: { height: "100dvh", position: "relative", overflow: "hidden", bg: "bg.subtle" },
    window: {
      display: "flex",
      flexDirection: "column",
      height: "full",
      width: "full",
      position: "relative",
      bg: "bg.subtle",
      color: "fg",
      overflow: "hidden",
    },
    titlebar: {
      height: "11",
      flexShrink: 0,
      gap: "xs",
      px: "compact",
      display: { base: "none", lg: "flex" },
      alignItems: "center",
    },
    windowControls: { display: "flex", alignItems: "center", gap: "xs", px: "sm", flexShrink: 0 },
    actionMenuButton: { marginInlineStart: "auto", flexShrink: 0 },
    windowControl: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "icon-2xs",
      height: "icon-2xs",
      borderRadius: "full",
      color: "blackAlpha.700",
      cursor: "pointer",
      "& svg": { width: "2", height: "2", visibility: "hidden" },
      "&[data-control=close]:not(:disabled)": { bg: "windowControl.close" },
      "&[data-control=minimize]:not(:disabled)": { bg: "windowControl.minimize" },
      "&[data-control=zoom]": { bg: "windowControl.zoom" },
      _groupHover: { "&:not(:disabled) svg": { visibility: "visible" } },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "fg",
        outlineOffset: "2px",
        "& svg": { visibility: "visible" },
      },
      _disabled: { bg: "bg.muted", cursor: "not-allowed", "& svg": { visibility: "hidden" } },
    },
    mobileTitlebar: {
      height: "mobile-titlebar",
      flexShrink: 0,
      px: "sm",
      display: { base: "flex", lg: "none" },
      alignItems: "center",
      justifyContent: "space-between",
    },
    sidebar: {
      display: "flex",
      flexDirection: "column",
      layerStyle: "panel",
      height: "full",
      width: "full",
      flexShrink: 0,
      gap: "2xs",
      px: "xs",
      py: "xs",
      bg: "bg.subtle",
    },
    sidebarScroll: { flex: 1, minHeight: 0, width: "full" },
    sidebarRows: { display: "flex", flexDirection: "column", gap: "2xs" },
    sidebarHeading: {
      display: "flex",
      alignItems: "center",
      minHeight: "7",
      mt: "sm",
      px: "xs",
      textStyle: "label/XS",
      color: "fg.subtle",
      textTransform: "uppercase",
    },
    sidebarFooter: {
      display: "flex",
      flexDirection: "column",
      gap: "2xs",
      pt: "xs",
      borderTopWidth: "1px",
      borderColor: "border.subtle",
    },
    status: {
      minHeight: "7",
      flexShrink: 0,
      flexWrap: "wrap",
      gap: "xs",
      rowGap: "2xs",
      px: "xs",
      color: "fg.muted",
    },
    copyright: { textStyle: { base: "label/XS", md: "label/S/medium" }, whiteSpace: "nowrap" },
    releaseBadge: { bg: "illustration.skill", color: "white" },
    body: { display: "flex", flex: 1, minHeight: 0, p: "panel-gap" },
    main: {
      flex: 1,
      minHeight: 0,
      minWidth: 0,
      position: "relative",
      overflow: "hidden",
      // A short load shows nothing; a slow one dims the page that stays in place.
      "&[aria-busy=true]": { opacity: 0.5, transition: "opacity 120ms ease 150ms" },
    },
    hero: {
      flex: 1,
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
      layerStyle: "panel",
      bg: "bg",
      width: "full",
      height: "full",
      overflow: "hidden",
      containerType: "inline-size",
      containerName: "hero",
      "& > [data-part=root] > [data-part=viewport] > [data-part=content]": {
        display: "flex",
        flexDirection: "column",
        minHeight: "full",
      },
    },
    heroLayout: {
      position: "relative",
      pb: "24",
      flex: "1 0 auto",
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      alignItems: "start",
      minHeight: "full",
      width: "full",
      mx: "auto",
      "@container hero (min-width: 54rem)": { gridTemplateColumns: "30rem minmax(0, 1fr)", pb: "4" },
    },
    cardSpace: {
      position: "relative",
      alignSelf: "stretch",
      containerType: "size",
      containerName: "board-area",
      minHeight: "var(--assembly-min-height)",
      "--assembly-min-height": "32rem",
      "--assembly-horizontal-space": "32px",
      "--assembly-bottom-space": "96px",
      "--assembly-board-scale": BOARD_SCALE.narrow,
      "@container hero (min-width: 54rem)": {
        "--assembly-min-height": "36rem",
        "--assembly-horizontal-space": "48px",
        "--assembly-bottom-space": "16px",
        "--assembly-board-scale": BOARD_SCALE.wide,
      },
    },
    heroCopy: {
      position: "relative",
      zIndex: 1,
      pointerEvents: "none",
      "& a, & button": { pointerEvents: "auto" },
      display: "flex",
      flexDirection: "column",
      width: "full",
      maxWidth: "2xl",
      mx: "auto",
      gap: "xl",
      px: { base: "lg", xl: "3xl" },
      py: { base: "xl", xl: "4xl" },
      "@container hero (min-width: 54rem)": { gap: "md", py: "lg" },
    },
    download: { display: "flex", flexDirection: "column", gap: "sm", alignItems: "start", width: "full" },
    downloadDescription: { minHeight: "12" },
    downloadPlatforms: { minHeight: "8", gap: "xs" },
    siteTabs: { gap: "2xs", flexShrink: 1, minWidth: 0, overflowX: "auto" },
    siteTab: {
      display: "flex",
      alignItems: "center",
      height: "7",
      px: "compact",
      gap: "xs",
      borderRadius: "xs",
      borderWidth: "1px",
      borderColor: "transparent",
      color: "fg.muted",
      flexShrink: 0,
      cursor: "pointer",
      focusVisibleRing: "outside",
      _hover: { bg: "bg.hover", color: "fg" },
      "&[aria-current=page]": { bg: "bg.hover", color: "fg", borderColor: "border.subtle" },
    },
    siteTabIcon: { boxSize: "icon-sm", flexShrink: 0, "& svg": { width: "full", height: "full" } },
    siteTabLabel: { fontFamily: "heading", textStyle: "label/S/medium", whiteSpace: "nowrap" },
  },
  variants: {
    windowed: {
      true: {
        root: { bg: "illustration.desktop" },
        window: {
          height: "calc(100dvh - 12rem)",
          width: "calc(100% - 15rem)",
          mx: "7.5rem",
          my: "6rem",
          borderRadius: "lg",
          boxShadow: "2xl",
        },
        titlebar: { cursor: "grab", _active: { cursor: "grabbing" } },
      },
    },
  },
});
