import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { $ } from "bun";

// Ensure we run from the repo root regardless of where the script is invoked
process.chdir(join(import.meta.dirname, ".."));

const DASHBOARD_DIST = "./packages/pstdio-dashboard/dist";
const CLI_FILES = "./packages/pstdio/files";
const DRIZZLE_DIR = "./packages/pstdio-db/drizzle";
const CLI_ENTRY = "./packages/pstdio/src/index.ts";
const EMBED_MANIFEST = "./packages/pstdio/src/_embed-manifest.generated.ts";

const collectFiles = (dir: string): string[] => {
  const files: string[] = [];

  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".")) continue;
    const fullPath = join(dir, entry);

    if (statSync(fullPath).isDirectory()) {
      files.push(...collectFiles(fullPath));
    } else {
      files.push(fullPath);
    }
  }

  return files;
};

// 1. Build all packages
console.log("Building packages...");
await $`bun run --filter pstdio-dashboard build`;
await $`bun run --filter pstdio-api build`;

// 2. Collect files for embedding (dashboard assets + bundled files + PGlite + drizzle)
console.log("Collecting files to embed...");
const distFiles = collectFiles(DASHBOARD_DIST);
const cliFiles = collectFiles(CLI_FILES);
const drizzleFiles = collectFiles(DRIZZLE_DIR);
const pgliteFiles = [join(PGLITE_DIST, "pglite.data"), join(PGLITE_DIST, "pglite.wasm")];
const allFiles = [...distFiles, ...cliFiles, ...drizzleFiles, ...pgliteFiles];

console.log(
  `  Found ${allFiles.length} files to embed (${distFiles.length} dashboard + ${cliFiles.length} bundled + ${drizzleFiles.length} drizzle + ${pgliteFiles.length} pglite)`,
);

// 3. Generate embed manifest — imports each file with { type: "file" } so Bun embeds them
const manifestDir = join("packages", "pstdio", "src");
const imports = allFiles
  .map((f) => {
    const rel = relative(manifestDir, f).replaceAll("\\", "/");
    return `import "./${rel}" with { type: "file" };`;
  })
  .join("\n");

writeFileSync(EMBED_MANIFEST, `// AUTO-GENERATED by build-compile.ts — do not edit\n${imports}\n`);
console.log(`  Generated embed manifest: ${EMBED_MANIFEST}`);

// 4. Compile for local platform
const target = `bun-${process.platform}-${process.arch}`;
const outfile = "./dist/pstdio";

console.log(`\nCompiling for ${target}...`);
await $`bun build ${CLI_ENTRY} --compile --target=${target} --asset-naming [dir]/[name].[ext] --outfile ${outfile}`;

// 5. Verify the binary works
const version = await $`${outfile} --version`.text();
console.log(`\nCompiled binary: ${join(process.cwd(), outfile)}`);
console.log(`  Version: ${version.trim()}`);
