import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { $ } from "bun";
import { loadEmbedConfig, resolveEmbedFiles } from "./lib/embed-manifest";

// Ensure we run from the repo root regardless of where the script is invoked
process.chdir(join(import.meta.dirname, ".."));

const CLI_ENTRY = "./packages/pstdio/src/index.ts";
const EMBED_MANIFEST = "./packages/pstdio/src/_embed-manifest.generated.ts";

// 1. Build all packages
console.log("Building packages...");
await $`bun run --filter pstdio-dashboard build`;
await $`bun run --filter pstdio-api build`;

// 2. Resolve files to embed from the checked-in allowlist
console.log("Resolving embed manifest from scripts/embed.json...");
const config = loadEmbedConfig();
const allFiles = resolveEmbedFiles(config);
console.log(
  `  Resolved ${allFiles.length} files to embed (${config.files.length} explicit + ${allFiles.length - config.files.length} from globs)`,
);

// 3. Generate embed manifest — imports each file with { type: "file" } so Bun embeds them
const manifestDir = join("packages", "pstdio", "src");
const imports = allFiles
  .map((f) => `import "./${relative(manifestDir, f).replaceAll("\\", "/")}" with { type: "file" };`)
  .join("\n");

writeFileSync(EMBED_MANIFEST, `// AUTO-GENERATED by build-all.ts from scripts/embed.json — do not edit\n${imports}\n`);
console.log(`  Generated embed manifest: ${EMBED_MANIFEST}`);

// 4. Compile for each target
for (const { target, pkg, bin } of config.buildTargets) {
  const outDir = `./packages/pstdio/dist/platforms/${pkg}/bin`;
  mkdirSync(outDir, { recursive: true });

  const outfile = join(outDir, bin);
  console.log(`\nCompiling for ${target}...`);
  await $`bun build ${CLI_ENTRY} --compile --target=${target} --asset-naming [dir]/[name].[ext] --outfile ${outfile}`;
  console.log(`  → ${relative(".", outfile)}`);
}

console.log("\nAll targets compiled.");
