import { mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { $ } from "bun";

// Ensure we run from the repo root regardless of where the script is invoked
process.chdir(join(import.meta.dirname, ".."));

const DASHBOARD_DIST = "./packages/pstdio-dashboard/dist";
const CLI_FILES = "./packages/pstdio/files";
const DRIZZLE_DIR = "./packages/pstdio-db/drizzle";
const CLI_ENTRY = "./packages/pstdio/src/index.ts";
const EMBED_MANIFEST = "./packages/pstdio/src/_embed-manifest.generated.ts";

const TARGETS = [
  { target: "bun-darwin-arm64", pkg: "cli-darwin-arm64", bin: "pstdio" },
  { target: "bun-darwin-x64", pkg: "cli-darwin-x64", bin: "pstdio" },
  { target: "bun-linux-x64", pkg: "cli-linux-x64", bin: "pstdio" },
  { target: "bun-linux-arm64", pkg: "cli-linux-arm64", bin: "pstdio" },
  { target: "bun-linux-x64-musl", pkg: "cli-linux-x64-musl", bin: "pstdio" },
  { target: "bun-linux-arm64-musl", pkg: "cli-linux-arm64-musl", bin: "pstdio" },
  { target: "bun-windows-x64", pkg: "cli-win-x64", bin: "pstdio.exe" },
  { target: "bun-windows-arm64", pkg: "cli-win-arm64", bin: "pstdio.exe" },
];

const collectFiles = (dir: string): string[] => {
  const files: string[] = [];

  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".")) continue;
    const fullPath = join(dir, entry);

    if (statSync(fullPath).isDirectory()) {
      files.push(...collectFiles(fullPath));
    } else {
      files.push(fullPath);
    }
  }

  return files;
};

// 1. Build all packages
console.log("Building packages...");
await $`bun run --filter pstdio-dashboard build`;
await $`bun run --filter pstdio-api build`;

// 2. Collect files for embedding (dashboard assets + bundled files + PGlite + drizzle)
console.log("Collecting files to embed...");
const distFiles = collectFiles(DASHBOARD_DIST);
const cliFiles = collectFiles(CLI_FILES);
const drizzleFiles = collectFiles(DRIZZLE_DIR);
const allFiles = [...distFiles, ...cliFiles, ...drizzleFiles];

console.log(
  `  Found ${allFiles.length} files to embed (${distFiles.length} dashboard + ${cliFiles.length} bundled + ${drizzleFiles.length} drizzle)`,
);

// 3. Generate embed manifest — imports each file with { type: "file" } so Bun embeds them
const manifestDir = join("packages", "pstdio", "src");
const imports = allFiles
  .map((f) => {
    const rel = relative(manifestDir, f).replaceAll("\\", "/");
    return `import "./${rel}" with { type: "file" };`;
  })
  .join("\n");

writeFileSync(EMBED_MANIFEST, `// AUTO-GENERATED by build-all.ts — do not edit\n${imports}\n`);
console.log(`  Generated embed manifest: ${EMBED_MANIFEST}`);

// 4. Compile for each target
for (const { target, pkg, bin } of TARGETS) {
  const outDir = `./packages/pstdio/dist/platforms/${pkg}/bin`;
  mkdirSync(outDir, { recursive: true });

  const outfile = join(outDir, bin);
  console.log(`\nCompiling for ${target}...`);
  await $`bun build ${CLI_ENTRY} --compile --target=${target} --asset-naming [dir]/[name].[ext] --outfile ${outfile}`;
  console.log(`  → ${relative(".", outfile)}`);
}

console.log("\nAll targets compiled.");
