import { defineSlotRecipe } from "@chakra-ui/react";

export const landingToolDemoSlotRecipe = defineSlotRecipe({
  slots: [
    "iconEditor",
    "iconGrid",
    "iconTile",
    "iconName",
    "tileSymbol",
    "iconCanvas",
    "inspectorSymbol",
    "inspector",
    "toolbar",
    "metrics",
    "metric",
    "sessions",
    "session",
    "sessionStatus",
    "preview",
    "checks",
    "prompt",
    "plot",
    "plotGrid",
    "plotCurve",
    "plotCursor",
    "plotPoint",
  ],
  base: {
    plot: { width: "full", bg: "bg.subtle", borderRadius: "sm" },
    plotGrid: { fill: "none", stroke: "border.subtle", strokeWidth: 1 },
    plotCurve: { fill: "none", stroke: "fg.info", strokeWidth: 3, strokeLinecap: "round", strokeLinejoin: "round" },
    plotCursor: { stroke: "fg.muted", strokeWidth: 1, strokeDasharray: "4 4" },
    plotPoint: { fill: "fg", stroke: "bg", strokeWidth: 2 },
    iconEditor: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "panel-gap",
      "@container (min-width: 36rem)": { gridTemplateColumns: "minmax(0, 1.5fr) minmax(0, 1fr)" },
    },
    iconGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(min({sizes.24}, 100%), 1fr))",
      gap: "xs",
      listStyle: "none",
      py: "xs",
    },
    iconTile: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "xs",
      minWidth: 0,
      minHeight: "28",
      p: "sm",
      bg: "bg.subtle",
      borderWidth: "1px",
      borderColor: "border.subtle",
      borderRadius: "sm",
      color: "fg",
      transitionProperty: "opacity, background-color, border-color",
      transitionDuration: "moderate",
      "&[data-state=pending]": { opacity: 0.25 },
      "&[data-state=active]": { borderColor: "fg.info", bg: "bg.info" },
      "@media (prefers-reduced-motion: reduce)": { transition: "none" },
      "&[aria-pressed]": { cursor: "pointer", _hover: { bg: "bg.hover" } },
      _focusVisible: { outline: "2px solid", outlineColor: "fg", outlineOffset: "2px" },
      "&[aria-pressed=true]": { borderColor: "fg.info", bg: "bg.info" },
    },
    iconName: {
      textStyle: "label/S/regular",
      maxWidth: "full",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    tileSymbol: { boxSize: "8", fontSize: "{sizes.8}", mb: "xs" },
    iconCanvas: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      bg: "bg.subtle",
      borderRadius: "sm",
      minHeight: "44",
      p: "xl",
    },
    inspectorSymbol: { boxSize: "24", fontSize: "{sizes.24}" },
    inspector: { display: "flex", flexDirection: "column", gap: "md" },
    toolbar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "sm", flexWrap: "wrap" },
    metrics: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "panel-gap" },
    metric: { layerStyle: "panel", bg: "bg", p: "md", display: "flex", flexDirection: "column", gap: "xs" },
    sessions: { display: "flex", flexDirection: "column", gap: "sm", listStyle: "none" },
    session: {
      display: "flex",
      flexDirection: "column",
      gap: "md",
      width: "full",
      p: "md",
      minWidth: 0,
      textAlign: "left",
      color: "fg",
      layerStyle: "panel",
      bg: "bg.subtle",
      "&[aria-pressed]": { cursor: "pointer", _hover: { bg: "bg.hover" } },
      _focusVisible: { outline: "2px solid", outlineColor: "fg", outlineOffset: "2px" },
      "&[aria-pressed=true]": { borderColor: "fg.muted", bg: "bg.active" },
      "&[data-status=in_progress]": { borderColor: "fg.info", bg: "bg.info" },
      "&[data-status=completed]": { borderColor: "fg.success" },
    },
    sessionStatus: {
      gap: "xs",
      "&[data-status=in_progress] > svg": { animation: "spin 1.2s linear infinite" },
      "@media (prefers-reduced-motion: reduce)": { "&[data-status=in_progress] > svg": { animation: "none" } },
    },
    preview: { layerStyle: "panel", bg: "bg.subtle", p: "md", overflow: "hidden", minWidth: 0, flex: 1 },
    checks: { display: "flex", flexWrap: "wrap", gap: "md", textStyle: "label/S/regular", color: "fg.success" },
    prompt: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexWrap: "wrap",
      gap: "md",
      p: "lg",
      bg: "bg.subtle",
      layerStyle: "panel",
      textStyle: "paragraph/L/regular",
    },
  },
});
