import { defineSlotRecipe } from "@chakra-ui/react";

export const landingStorySlotRecipe = defineSlotRecipe({
  slots: [
    "page",
    "section",
    "featureSection",
    "intro",
    "visual",
    "panels",
    "panel",
    "panelHeader",
    "panelBody",
    "blockGrid",
    "block",
    "blockSymbol",
    "blockMark",
    "composition",
  ],
  base: {
    page: {
      display: "flex",
      flexDirection: "column",
      width: "full",
      minWidth: 0,
      gap: "4xl",
      px: { base: "lg", md: "xl" },
      py: "3xl",
      containerType: "inline-size",
    },
    section: { display: "flex", flexDirection: "column", gap: "lg", width: "full", minWidth: 0 },
    featureSection: {
      display: "flex",
      flexDirection: "column",
      gap: "xl",
      width: "full",
      minWidth: 0,
      borderTopWidth: "1px",
      borderColor: "border",
      pt: "4xl",
      pb: "xl",
    },
    intro: { display: "flex", flexDirection: "column", gap: "sm", maxWidth: "3xl" },
    visual: { layerStyle: "panel", bg: "bg.subtle", p: "xs", width: "full", minWidth: 0 },
    panels: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "panel-gap",
      "@container (min-width: 36rem)": { gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.3fr)" },
    },
    panel: {
      layerStyle: "panel",
      bg: "bg",
      minWidth: 0,
      height: "full",
      display: "flex",
      flexDirection: "column",
      "&[data-highlighted=true]": { borderColor: "fg.muted" },
    },
    panelHeader: {
      display: "flex",
      alignItems: "center",
      gap: "sm",
      p: "md",
      borderBottomWidth: "1px",
      borderColor: "border.subtle",
      textStyle: "label/M/medium",
    },
    panelBody: { display: "flex", flexDirection: "column", gap: "md", p: "md", flex: 1, minWidth: 0 },
    blockGrid: {
      display: "grid",
      gap: "sm",
      gridTemplateColumns: "minmax(0, 1fr)",
      "@container (min-width: 26rem)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
      "@container (min-width: 55rem)": { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
    },
    block: {
      display: "flex",
      flexDirection: "column",
      alignItems: "start",
      gap: "sm",
      p: "lg",
      bg: "bg.subtle",
      borderRadius: "sm",
      borderWidth: "1px",
      borderColor: "border.subtle",
      textAlign: "left",
      color: "fg",
    },
    blockMark: { display: "inline-flex", flexShrink: 0, "& svg": { height: "full", width: "auto", maxWidth: "none" } },
    blockSymbol: { display: "flex", alignItems: "center", justifyContent: "start", height: "16", width: "full" },
    composition: {
      display: "flex",
      flexDirection: "column",
      gap: "md",
      borderTopWidth: "1px",
      borderColor: "border.subtle",
      pt: "lg",
    },
  },
});
