import { defineSlotRecipe } from "@chakra-ui/react";

export const landingToolDemoSlotRecipe = defineSlotRecipe({
  slots: [
    "glyphs",
    "glyph",
    "canvas",
    "art",
    "grid",
    "guide",
    "specimen",
    "toolbar",
    "metrics",
    "metric",
    "sessions",
    "session",
    "progress",
    "segment",
    "preview",
    "file",
    "checks",
    "prompt",
  ],
  base: {
    glyphs: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: "xs" },
    glyph: {
      textStyle: "heading/M",
      py: "sm",
      bg: "bg.subtle",
      borderWidth: "1px",
      borderColor: "border.subtle",
      borderRadius: "sm",
      cursor: "pointer",
      color: "fg",
      _hover: { bg: "bg.hover" },
      _focusVisible: { outline: "2px solid", outlineColor: "fg", outlineOffset: "2px" },
      "&[aria-pressed=true]": { borderColor: "fg.info", bg: "bg.info" },
    },
    canvas: { bg: "bg.subtle", borderRadius: "sm", overflow: "hidden", minWidth: 0 },
    art: {
      display: "block",
      width: "full",
      height: "auto",
      fontFamily: "heading",
      color: "fg",
      "& text": { fontWeight: "inherit" },
      "&[data-weight='400']": { fontWeight: "regular" },
      "&[data-weight='500']": { fontWeight: "medium" },
      "&[data-weight='600']": { fontWeight: "semibold" },
      "&[data-weight='700']": { fontWeight: "bold" },
      "& [data-type=glyph]": { fontSize: "calc({fontSizes.7xl} * 3)" },
      "& [data-type=display]": { fontSize: "calc({fontSizes.7xl} * 1.5)" },
      "& [data-type=heading]": { fontSize: "6xl" },
      "& [data-type=alphabet]": { fontSize: "5xl" },
      "& [data-type=label]": { fontSize: "2xl" },
      "& [data-type=metric]": { textStyle: "mono/XS" },
    },
    grid: { color: "border" },
    guide: { color: "fg.info" },
    specimen: { display: "flex", flexDirection: "column", justifyContent: "center", minHeight: "72", flex: 1 },
    toolbar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "sm", flexWrap: "wrap" },
    metrics: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "panel-gap" },
    metric: { layerStyle: "panel", bg: "bg", p: "md", display: "flex", flexDirection: "column", gap: "xs" },
    sessions: { display: "flex", flexDirection: "column", gap: "sm" },
    session: {
      display: "flex",
      flexDirection: "column",
      gap: "md",
      width: "full",
      p: "md",
      minWidth: 0,
      textAlign: "left",
      color: "fg",
      layerStyle: "panel",
      bg: "bg.subtle",
      cursor: "pointer",
      _hover: { bg: "bg.hover" },
      _focusVisible: { outline: "2px solid", outlineColor: "fg", outlineOffset: "2px" },
      "&[aria-pressed=true]": { borderColor: "fg.muted", bg: "bg.active" },
    },
    progress: { display: "grid", gridTemplateColumns: "repeat(16, minmax(0, 1fr))", gap: "2xs", width: "full" },
    segment: {
      height: "2",
      bg: "bg.muted",
      borderRadius: "xs",
      "&[data-filled=true]": { bg: "fg.info" },
      "&[data-status=completed][data-filled=true]": { bg: "fg.success" },
      "&[data-status=awaiting_input][data-filled=true]": { bg: "fg.warning" },
    },
    preview: { layerStyle: "panel", bg: "bg.subtle", p: "md", overflow: "hidden", minWidth: 0, flex: 1 },
    file: {
      display: "flex",
      alignItems: "center",
      gap: "sm",
      py: "sm",
      textStyle: "mono/XS",
      minWidth: 0,
      borderBottomWidth: "1px",
      borderColor: "border.subtle",
      "&:last-child": { borderBottomWidth: 0 },
    },
    checks: { display: "flex", flexWrap: "wrap", gap: "md", textStyle: "label/S/regular", color: "fg.success" },
    prompt: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexWrap: "wrap",
      gap: "md",
      p: "lg",
      bg: "bg.subtle",
      layerStyle: "panel",
      textStyle: "paragraph/L/regular",
    },
  },
});
