import { defineSlotRecipe } from "@chakra-ui/react";

export const landingSlotRecipe = defineSlotRecipe({
  slots: [
    "root",
    "window",
    "titlebar",
    "windowControls",
    "windowControl",
    "mobileTitlebar",
    "mobileNav",
    "sidebar",
    "status",
    "body",
    "main",
    "hero",
    "heroCopy",
    "tools",
    "download",
    "brandTab",
    "panelsScroll",
    "panelScroll",
  ],
  base: {
    root: { height: "100dvh", position: "relative", overflow: "hidden", bg: "bg.subtle" },
    window: {
      display: "flex",
      flexDirection: "column",
      height: "full",
      width: "full",
      position: "relative",
      bg: "bg.subtle",
      color: "fg",
      overflow: "hidden",
    },
    titlebar: {
      height: "11",
      flexShrink: 0,
      gap: "xs",
      px: "compact",
      display: { base: "none", md: "flex" },
      alignItems: "center",
    },
    windowControls: { display: "flex", alignItems: "center", gap: "xs", px: "sm", flexShrink: 0 },
    windowControl: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "icon-2xs",
      height: "icon-2xs",
      borderRadius: "full",
      color: "blackAlpha.700",
      cursor: "pointer",
      "& svg": { width: "2", height: "2", visibility: "hidden" },
      "&[data-control=close]:not(:disabled)": { bg: "windowControl.close" },
      "&[data-control=minimize]:not(:disabled)": { bg: "windowControl.minimize" },
      "&[data-control=zoom]": { bg: "windowControl.zoom" },
      _groupHover: { "&:not(:disabled) svg": { visibility: "visible" } },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "fg",
        outlineOffset: "2px",
        "& svg": { visibility: "visible" },
      },
      _disabled: { bg: "bg.muted", cursor: "not-allowed", "& svg": { visibility: "hidden" } },
    },
    mobileTitlebar: {
      height: "mobile-titlebar",
      flexShrink: 0,
      gap: "xs",
      px: "sm",
      display: { base: "flex", md: "none" },
      textAlign: "left",
      alignItems: "center",
    },
    mobileNav: {
      alignItems: "center",
      height: "10",
      flexShrink: 0,
      width: "full",
      gap: "xs",
      px: "md",
      display: { base: "flex", lg: "none" },
    },
    sidebar: {
      display: "flex",
      flexDirection: "column",
      layerStyle: "panel",
      height: "full",
      width: "full",
      flexShrink: 0,
      gap: "2xs",
      px: "xs",
      py: "xs",
      bg: "bg.subtle",
    },
    status: {
      minHeight: "7",
      flexShrink: 0,
      flexWrap: "wrap",
      gap: "xs",
      rowGap: "2xs",
      px: "xs",
      color: "fg.muted",
    },
    body: { display: "flex", flex: 1, minHeight: 0, p: "panel-gap" },
    main: { flex: 1, minHeight: 0, minWidth: 0, position: "relative", overflow: "hidden" },
    panelsScroll: {
      "& > [data-part=viewport] > [data-part=content]": { height: { base: "auto", lg: "full" } },
      "& > [data-part=scrollbar]": { display: { base: "flex", lg: "none" } },
    },
    panelScroll: {
      display: { base: "contents", lg: "flex" },
      "& > [data-part=viewport]": { display: { base: "contents", lg: "block" } },
      "& > [data-part=viewport] > [data-part=content]": { display: { base: "contents", lg: "block" } },
      "& > [data-part=scrollbar]": { display: { base: "none", lg: "flex" } },
    },
    hero: { layerStyle: "panel", bg: "bg", width: "full", height: "full", overflow: "hidden" },
    heroCopy: {
      display: "flex",
      flexDirection: "column",
      minHeight: "full",
      width: "full",
      maxWidth: "2xl",
      mx: "auto",
      gap: "xl",
      px: { base: "lg", xl: "3xl" },
      py: { base: "xl", xl: "4xl" },
    },
    tools: {
      layerStyle: "panel",
      bg: "bg",
      position: "relative",
      overflow: "hidden",
      width: "full",
      height: "full",
      minHeight: "0",
    },
    download: { display: "flex", flexDirection: "column", gap: "sm", alignItems: "start", width: "full" },
    brandTab: {
      height: "7",
      px: "compact",
      gap: "xs",
      borderRadius: "xs",
      bg: "bg.hover",
      color: "fg",
      borderWidth: "1px",
      borderColor: "border.subtle",
      flexShrink: 0,
      cursor: "pointer",
    },
  },
  variants: {
    windowed: {
      true: {
        root: { bg: "illustration.desktop" },
        window: {
          height: "calc(100dvh - 12rem)",
          width: "calc(100% - 15rem)",
          mx: "7.5rem",
          my: "6rem",
          borderRadius: "lg",
          boxShadow: "2xl",
        },
        titlebar: { cursor: "grab", _active: { cursor: "grabbing" } },
      },
    },
  },
});
