import { defineSlotRecipe } from "@chakra-ui/react";

export const landingStorySlotRecipe = defineSlotRecipe({
  slots: [
    "page",
    "section",
    "intro",
    "visual",
    "visualHeader",
    "panels",
    "panel",
    "panelHeader",
    "panelBody",
    "row",
    "blockGrid",
    "block",
    "blockSymbol",
    "blockMark",
    "composition",
    "service",
    "prompt",
    "flow",
    "caption",
  ],
  base: {
    page: {
      display: "flex",
      flexDirection: "column",
      width: "full",
      minWidth: 0,
      gap: "4xl",
      px: { base: "lg", md: "xl" },
      py: "3xl",
      containerType: "inline-size",
    },
    section: { display: "flex", flexDirection: "column", gap: "lg", width: "full", minWidth: 0 },
    intro: { display: "flex", flexDirection: "column", gap: "sm", maxWidth: "3xl" },
    visual: { layerStyle: "panel", bg: "bg.subtle", p: "xs", width: "full", minWidth: 0 },
    visualHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "sm",
      px: "sm",
      py: "sm",
      color: "fg.muted",
      textStyle: "label/S/regular",
      flexWrap: "wrap",
    },
    panels: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "panel-gap",
      "@container (min-width: 36rem)": { gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.3fr)" },
    },
    panel: {
      layerStyle: "panel",
      bg: "bg",
      minWidth: 0,
      height: "full",
      display: "flex",
      flexDirection: "column",
      "&[data-highlighted=true]": { borderColor: "fg.muted" },
    },
    panelHeader: {
      display: "flex",
      alignItems: "center",
      gap: "sm",
      p: "md",
      borderBottomWidth: "1px",
      borderColor: "border.subtle",
      textStyle: "label/M/medium",
    },
    panelBody: { display: "flex", flexDirection: "column", gap: "md", p: "md", flex: 1, minWidth: 0 },
    row: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "sm",
      py: "sm",
      borderBottomWidth: "1px",
      borderColor: "border.subtle",
      "&:last-child": { borderBottomWidth: 0 },
    },
    blockGrid: {
      display: "grid",
      gap: "sm",
      gridTemplateColumns: "minmax(0, 1fr)",
      "@container (min-width: 26rem)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
      "@container (min-width: 55rem)": { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
    },
    block: {
      display: "flex",
      flexDirection: "column",
      alignItems: "start",
      gap: "sm",
      p: "lg",
      bg: "bg.subtle",
      borderRadius: "sm",
      borderWidth: "1px",
      borderColor: "border.subtle",
      textAlign: "left",
      cursor: "pointer",
      color: "fg",
      _hover: { bg: "bg.hover" },
      _focusVisible: { outline: "2px solid", outlineColor: "fg", outlineOffset: "2px" },
      "&[aria-pressed=true]": { borderColor: "fg.muted", bg: "bg.active" },
    },
    blockMark: { display: "inline-flex", flexShrink: 0, "& svg": { height: "full", width: "auto", maxWidth: "none" } },
    blockSymbol: { display: "flex", alignItems: "center", justifyContent: "start", height: "16", width: "full" },
    composition: {
      display: "flex",
      flexDirection: "column",
      gap: "md",
      borderTopWidth: "1px",
      borderColor: "border.subtle",
      pt: "lg",
    },
    service: {
      display: "grid",
      gridTemplateColumns: "auto minmax(0, 1fr)",
      gap: "md",
      py: "lg",
      borderBottomWidth: "1px",
      borderColor: "border.subtle",
      "&:last-child": { borderBottomWidth: 0 },
    },
    prompt: { display: "flex", flexDirection: "column", gap: "md", p: "lg", bg: "bg.subtle", layerStyle: "panel" },
    flow: { display: "flex", gap: "xs", flexWrap: "wrap", alignItems: "center" },
    caption: { textStyle: "label/S/regular", color: "fg.muted" },
  },
});
