import { defineSlotRecipe } from "@chakra-ui/react";

export const queuedFollowUpRecipe = defineSlotRecipe({
  slots: ["root", "row", "actions", "sendNow", "draft", "notice", "handle", "content", "sendNowHit"],
  base: {
    content: {
      display: "flex",
      flexDirection: "column",
      gap: "2xs",
      textAlign: "left",
      bg: "transparent",
      border: 0,
      p: 0,
      color: "inherit",
      cursor: "pointer",
      width: "full",
      _focusVisible: { outline: "2px solid {colors.border.accent}", outlineOffset: "2px" },
    },
    sendNowHit: { position: "absolute", bottom: "100%", insetX: 0, h: "touch-target", zIndex: 2 },
    handle: { touchAction: "none", cursor: "grab", flexShrink: 0 },
    root: {
      position: "relative",
      minH: "0",
      flexShrink: 1,
      border: "border",
      borderBottomWidth: "0",
      borderTopRadius: "xs",
      bg: "bg",
      "&[data-dragging=true]": { borderTopRadius: "0" },
    },
    row: {
      position: "relative",
      display: "flex",
      gap: "xs",
      alignItems: "start",
      px: "xs",
      py: "xs",
      borderBottom: "border.subtle",
      textStyle: "label/S/regular",
      color: "fg",
      cursor: "pointer",
      "&[data-drag-source=true]": { opacity: 0.5 },
      "&[data-combine-target=true]": { bg: "bg.button.primary.default", color: "fg.button.primary.default" },
      _focusVisible: { outline: "2px solid {colors.border.accent}", outlineOffset: "-2px" },
    },
    actions: { opacity: 0, pointerEvents: "none", "&[data-visible=true]": { opacity: 1, pointerEvents: "auto" } },
    sendNow: {
      position: "absolute",
      bottom: "0",
      insetX: "0",
      height: "queue-send-now",
      borderTopRadius: "xs",
      borderBottomRadius: "0",
      borderWidth: "1px",
      borderBottomWidth: "0",
      borderStyle: "solid",
      borderColor: "transparent",
      backgroundImage:
        "linear-gradient(to right, {colors.border} 4px, transparent 4px), linear-gradient(to bottom, {colors.border} 4px, transparent 4px), linear-gradient(to bottom, {colors.border} 4px, transparent 4px)",
      backgroundSize: "8px 1px, 1px 8px, 1px 8px",
      backgroundRepeat: "repeat-x, repeat-y, repeat-y",
      backgroundPosition: "top left, top left, top right",
      backgroundOrigin: "border-box",
      bg: "transparent",
      color: "fg.muted",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "2xs",
      textStyle: "label/XS",
      zIndex: 2,
      "&::before": { content: '""', position: "absolute", insetX: "0", bottom: "0", height: "touch-target" },
      "&[data-targeted=true]": {
        bg: "bg.button.primary.default",
        color: "fg.button.primary.default",
        backgroundImage: "none",
        borderStyle: "solid",
        borderColor: "fg.button.primary.default/30",
      },
      "&[aria-disabled=true]": { color: "fg.subtle" },
    },
    draft: {
      border: "border",
      borderTopWidth: "0",
      borderBottomRadius: "xs",
      px: "xs",
      py: "xs",
      bg: "bg",
      color: "fg.muted",
      textStyle: "label/S/regular",
      cursor: "pointer",
      textAlign: "left",
    },
    notice: { px: "xs", py: "2xs", color: "fg.error", textStyle: "label/S/regular" },
  },
});
