import { defineSlotRecipe } from "@chakra-ui/react";

export const windowTitleBarRecipe = defineSlotRecipe({
  className: "ps-window-title-bar",
  slots: ["root", "content"],
  base: {
    root: {
      position: "relative",
      flexShrink: 0,
      width: "full",
      height: "window-title-bar",
      bg: "bg",
      color: "fg",
      userSelect: "none",
      WebkitAppRegion: "drag",
    },
    content: {
      display: "flex",
      alignItems: "center",
      gap: "xs",
      height: "full",
      minWidth: 0,
      paddingInline: "compact",
      "& button, & a, & input, & [role=tab]": { WebkitAppRegion: "no-drag" },
    },
  },
  variants: {
    controls: {
      mac: {
        content: {
          paddingInlineStart: "window-controls-mac",
          "[data-window-full-screen] &": { paddingInlineStart: "compact" },
        },
      },
      overlay: { content: { marginLeft: "env(titlebar-area-x, 0px)", width: "env(titlebar-area-width, 100%)" } },
    },
  },
  defaultVariants: { controls: "overlay" },
});

export const windowTabsRecipe = defineSlotRecipe({
  className: "ps-window-tabs",
  slots: ["list", "tab", "trigger", "label", "close"],
  base: {
    list: { display: "flex", alignItems: "center", gap: "2xs", minWidth: 0, overflowX: "auto", scrollbarWidth: "none" },
    tab: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      flexShrink: 0,
      height: "window-tab",
      maxWidth: "window-tab-max",
      borderRadius: "xs",
      borderWidth: "1px",
      borderColor: "border",
      color: "fg.muted",
      bg: "transparent",
      _selected: { bg: "bg.muted", color: "fg" },
      _hover: { bg: "bg.hover", color: "fg" },
      _dragging: { bg: "bg.hover", color: "fg", zIndex: "docked" },
      WebkitAppRegion: "no-drag",
    },
    trigger: {
      display: "flex",
      alignItems: "center",
      gap: "window-tab-gap",
      minWidth: 0,
      height: "full",
      paddingInlineStart: "compact",
      paddingInlineEnd: "window-tab-gap",
      cursor: "pointer",
      textStyle: "label/S/medium",
      borderRadius: "xs",
      focusVisibleRing: "inside",
      WebkitAppRegion: "no-drag",
      touchAction: "none",
      _icon: { width: "icon-xs", height: "icon-xs", flexShrink: 0 },
    },
    label: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    close: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      width: "window-tab-close",
      height: "window-tab-close",
      marginInlineEnd: "compact",
      color: "fg.muted",
      borderRadius: "2xs",
      cursor: "pointer",
      focusVisibleRing: "outside",
      WebkitAppRegion: "no-drag",
      _hover: { bg: "bg.active", color: "fg" },
      _icon: { width: "full", height: "full" },
    },
  },
});
