import { createClient } from "@pstdio/sdk/client";
import { createDb } from "pstdio-db";
import { loadExtensionRuntime, runExtensionCommand } from "pstdio-extensions";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { topLevelCommandModules, topLevelStaticCommandNames } from "./adapters/cli/commands";
import * as dashboardCommand from "./adapters/cli/commands/dashboard";
import {
  createExtensionCommandRegistry,
  formatUnavailableExtensionCommandMessage,
} from "./adapters/cli/commands/extension-command-modules";
import { createExtensionCommandSessions } from "./adapters/cli/commands/extension-command-sessions";
import { API_URL } from "./features/api-url";
import { CLI_VERSION } from "./features/cli-version";
import { findGitRoot, readConfig } from "./features/config/config";
import { ensureApi } from "./features/ensure-api";
import { createCliCommandTracker } from "./features/logging/cli-command-log";
import { resolveCliSessionId } from "./features/sessions/resolve-cli-session-id";
import { shouldBypassApiBootstrap } from "./features/should-bypass-api-bootstrap";
import { shouldLoadEmbedManifest } from "./features/should-load-embed-manifest";

if (shouldLoadEmbedManifest()) {
  // Side-effect import: registers files for Bun.embeddedFiles in compiled binaries.
  // Generated by build scripts.
  await import("./_embed-manifest.generated");
}

const resolveApiUrl = (argv: Record<string, unknown>) => {
  if (process.env.PSTDIO_API_URL) return process.env.PSTDIO_API_URL;

  const apiPort = argv["api-port"];
  if (typeof apiPort === "number") return `http://localhost:${apiPort}`;

  return API_URL;
};

const applyApiPortFromArgs = (argv: Record<string, unknown>) => {
  if (process.env.PSTDIO_API_URL || process.env.PSTDIO_API_PORT) return;

  const apiPort = argv["api-port"];
  if (typeof apiPort !== "number") return;

  process.env.PSTDIO_API_PORT = String(apiPort);
};

const rawArgs = hideBin(process.argv);

const globalOptionsWithValues = new Set(["--api-port", "--dashboard-port"]);

const resolveCommandPathFromRawArgs = (args: string[]) => {
  const pathSegments: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--") {
      const remaining = args.slice(index + 1);
      pathSegments.push(...remaining);
      break;
    }

    if (arg.startsWith("--")) {
      const equalsIndex = arg.indexOf("=");
      const optionName = equalsIndex >= 0 ? arg.slice(0, equalsIndex) : arg;
      if (globalOptionsWithValues.has(optionName) && equalsIndex < 0) {
        index += 1;
      }
      continue;
    }

    if (arg.startsWith("-")) continue;

    pathSegments.push(arg);
  }

  return pathSegments.join(" ");
};

const resolveTopLevelCommandFromRawArgs = (args: string[]) => {
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--") return args[index + 1] ?? null;

    if (arg.startsWith("--")) {
      const equalsIndex = arg.indexOf("=");
      const optionName = equalsIndex >= 0 ? arg.slice(0, equalsIndex) : arg;
      if (globalOptionsWithValues.has(optionName) && equalsIndex < 0) {
        index += 1;
      }
      continue;
    }

    if (arg.startsWith("-")) continue;

    return arg;
  }

  return null;
};

const shouldLoadExtensionRuntimeForArgs = (args: string[]) => {
  const command = resolveTopLevelCommandFromRawArgs(args);
  if (!command) return false;
  return !topLevelStaticCommandNames.includes(command);
};

const shouldShowUnavailableExtensionMessage = (
  reason: "duplicate_extension_path" | "static_command_collision" | "unsupported_extension_path",
) => reason !== "static_command_collision";

const resolveProjectContext = () => {
  const root = findGitRoot(process.cwd());
  if (!root) return null;
  const config = readConfig(root);
  if (!config) return null;
  return { root, config };
};

const projectContext = resolveProjectContext();
const projectRoot = projectContext?.root ?? null;
const shouldLoadExtensionRuntime = projectRoot ? shouldLoadExtensionRuntimeForArgs(rawArgs) : false;
const extensionRuntime = shouldLoadExtensionRuntime && projectRoot ? await loadExtensionRuntime({ projectRoot }) : null;
let extensionCommandArgv: Record<string, unknown> = {};
const extensionCommands = createExtensionCommandRegistry({
  cli: extensionRuntime?.cli ?? [],
  staticTopLevelCommands: topLevelStaticCommandNames,
  runCommand: async ({ commandId, params }) => {
    if (!extensionRuntime || !projectContext) {
      throw new Error("Extension command execution requires a Prompt Studio project.");
    }

    const connection = await createDb();
    try {
      const apiUrl = resolveApiUrl(extensionCommandArgv);
      const client = createClient({ baseUrl: apiUrl, token: process.env.PSTDIO_API_TOKEN });

      return await runExtensionCommand({
        commands: extensionRuntime.commands,
        db: connection.db,
        projectId: projectContext.config.project_id,
        commandId,
        params,
        sessions: createExtensionCommandSessions({
          projectId: projectContext.config.project_id,
          ensureApi: async () => {
            applyApiPortFromArgs(extensionCommandArgv);
            await ensureApi(apiUrl);
          },
          createSession: (input) => client.sessions.create(input),
        }),
      });
    } finally {
      await connection.close();
    }
  },
});

const commandTracker = createCliCommandTracker({
  rawArgs,
  sessionId: resolveCliSessionId({ env: process.env }),
});

const cli = yargs(rawArgs)
  .scriptName("pstdio")
  .version(CLI_VERSION)
  .strict()
  .fail((msg, err, yargs) => {
    const commandPath = resolveCommandPathFromRawArgs(rawArgs);
    const unavailable = extensionCommands.unavailableByPath.get(commandPath);
    if (unavailable && shouldShowUnavailableExtensionMessage(unavailable.reason)) {
      const message = formatUnavailableExtensionCommandMessage(unavailable);
      commandTracker.logFailure(message);
      process.stderr.write(`Error: ${message}\n`);
      process.exit(1);
    }

    commandTracker.logFailure(err ?? msg);
    if (err) {
      process.stderr.write(`Error: ${err.message}\n`);
      process.exit(1);
    }
    process.stderr.write(`${msg}\n\n`);
    yargs.showHelp("error");
    process.stderr.write("\n");
    process.exit(1);
  })
  .middleware(async (argv) => {
    extensionCommandArgv = argv;
    commandTracker.captureArgv(argv);
    commandTracker.logStart();

    const commandPath = argv._.map((value) => String(value)).join(" ");
    const unavailable = extensionCommands.unavailableByPath.get(commandPath);
    if (unavailable && shouldShowUnavailableExtensionMessage(unavailable.reason)) {
      throw new Error(formatUnavailableExtensionCommandMessage(unavailable));
    }

    const topLevelCommand = argv._[0];
    if (shouldBypassApiBootstrap(topLevelCommand)) return;
    if (shouldLoadExtensionRuntime) return;

    applyApiPortFromArgs(argv);
    await ensureApi(resolveApiUrl(argv));
  })
  .command(dashboardCommand);

for (const mod of topLevelCommandModules) {
  // biome-ignore lint/suspicious/noExplicitAny: yargs CommandModule union requires cast
  cli.command(mod as any);
}

for (const mod of extensionCommands.commandModules) {
  // biome-ignore lint/suspicious/noExplicitAny: yargs CommandModule union requires cast
  cli.command(mod as any);
}

cli
  .parseAsync()
  .then(() => {
    commandTracker.logSuccess();
  })
  .catch((error: unknown) => {
    commandTracker.logFailure(error);
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`Error: ${message}\n`);
    process.exit(1);
  });
