export const dashboardCommandIds = {
  createProject: "dashboard.createProject",
  createSession: "dashboard.createSession",
  createWorkspace: "dashboard.createWorkspace",
  deleteWorkspace: "dashboard.deleteWorkspace",
  openCommandPalette: "dashboard.openCommandPalette",
  openCurrentWorkspace: "dashboard.openCurrentWorkspace",
  openDiscord: "dashboard.openDiscord",
  openDocs: "dashboard.openDocs",
  openFile: "dashboard.openFile",
  openFloatingSession: "dashboard.openFloatingSession",
  openProjects: "dashboard.openProjects",
  openSessions: "dashboard.openSessions",
  openSettings: "dashboard.openSettings",
  openShortcuts: "dashboard.openShortcuts",
  openWorkspaces: "dashboard.openWorkspaces",
  productInfo: "dashboard.productInfo",
  selectWorkspaceSidebarSession: "dashboard.selectWorkspaceSidebarSession",
} as const;
