export {
  createArtifactMount,
  createFileMount,
  createWorkspaceFilesMount,
  isPackageAssetDescriptor,
  normalizeArtifactMountPath,
  normalizeCliPath,
  PackageAssetError,
  type PackageAssetKind,
  type ResolvedPackageAsset,
  readPackageAssetBytes,
  readPackageAssetText,
  resolvePackageAsset,
  resolvePackageAssetPath,
} from "./artifacts";

export {
  type BuildEnvironmentInput,
  buildCliHelpTree,
  type CheckExtensionsInput,
  type CheckExtensionsResult,
  type CliHelpNode,
  type CommandExecuteInput,
  type CommandRunner,
  type CommandRunnerEnvironment,
  type CommandRunnerHostDeps,
  checkExtensionHostCompatibility,
  checkExtensions,
  createCommandRunner,
  createDiagnostic,
  createExtensionInstallEnvironment,
  createExtensionProcessEnvironment,
  DEFAULT_MAX_COMMAND_DEPTH,
  dashboardExtensionHostCapabilities,
  discoverExtensionPackages,
  discoverExtensionPackagesInUserRoot,
  type ExtensionLoadScope,
  type ExtensionPackageRef,
  findFirstReservedKeybindingConflict,
  findReservedKeybindingConflict,
  findReservedKeybindingConflicts,
  formatCheckReport,
  type HostCommandExecuteInput,
  keybindingDedupeEntries,
  type LoadExtensionRuntimeInput,
  type LoadExtensionSourcesOptions,
  type LoadedExtensionSource,
  listReservedKeybindings,
  loadExtensionPackage,
  loadExtensionRuntime,
  loadExtensionSources,
  normalizeExtensionSources,
  type PackageManifest,
  pstdioExtensionsRoot,
  pstdioHomeRoot,
  type ReadPackageManifestResult,
  type ReservedKeybindingMatch,
  type ReservedKeybindingPlatform,
  type ReservedKeybindingReason,
  readPackageManifest,
  toCommandPaletteContributions,
} from "./runtime";
export { collectConventionDiagnostics } from "./runtime/conventions";
export { collectIconFontAssets } from "./runtime/normalize/icon-fonts";
export { workbenchIconNames } from "./runtime/workbench-icon-names";

export type * from "./types";
