import type { ThemePreference } from "./apply-theme-preference";

type ThemeCssVariables = Record<`--${string}`, string>;

const monokaiCssVariables = {
  "--chakra-colors-fg": "#F8F8F2",
  "--chakra-colors-fg-muted": "#CFCFC2",
  "--chakra-colors-fg-subtle": "#A59F85",
  "--chakra-colors-fg-inverted": "#272822",
  "--chakra-colors-bg": "#272822",
  "--chakra-colors-bg-subtle": "#1F201B",
  "--chakra-colors-bg-muted": "#34352E",
  "--chakra-colors-bg-hover": "#3E3D32",
  "--chakra-colors-bg-active": "#49483E",
  "--chakra-colors-bg-emphasized": "#49483E",
  "--chakra-colors-bg-inverted": "#F8F8F2",
  "--chakra-colors-bg-panel": "#1F201B",
  "--chakra-colors-bg-code": "#1F201B",
  "--chakra-colors-bg-dark": "#1F201B",
  "--chakra-colors-bg-button-primary-default": "#E6DB74",
  "--chakra-colors-bg-button-primary-hover": "#F4E98A",
  "--chakra-colors-bg-button-primary-pressed": "#CFC25F",
  "--chakra-colors-bg-menu-item-hover": "#3E3D32",
  "--chakra-colors-bg-menu-item-focus": "#3E3D32",
  "--chakra-colors-bg-menu-item-selected": "#49483E",
  "--chakra-colors-bg-accent-primary-default": "#E6DB74",
  "--chakra-colors-bg-accent-primary-hover": "#F4E98A",
  "--chakra-colors-bg-accent-primary-pressed": "#CFC25F",
  "--chakra-colors-bg-accent-primary-very-light": "#3B3A2B",
  "--chakra-colors-bg-accent-primary-light": "#494531",
  "--chakra-colors-bg-accent-primary-medium": "#E6DB74",
  "--chakra-colors-bg-accent-primary-dark": "#F4E98A",
  "--chakra-colors-bg-accent-secondary-grey-dark": "#272822",
  "--chakra-colors-bg-accent-secondary-grey-light": "#34352E",
  "--chakra-colors-bg-accent-secondary-red-very-light": "#3F2631",
  "--chakra-colors-bg-accent-secondary-red-light": "#5B2037",
  "--chakra-colors-bg-accent-secondary-pink-light": "#4A2039",
  "--chakra-colors-bg-accent-secondary-pink-medium": "#F92672",
  "--chakra-colors-bg-accent-secondary-blue-very-light": "#243A3D",
  "--chakra-colors-bg-accent-secondary-blue-light": "#26464A",
  "--chakra-colors-bg-accent-secondary-blue-medium": "#66D9EF",
  "--chakra-colors-bg-accent-secondary-blue-dark": "#66D9EF",
  "--chakra-colors-bg-accent-secondary-cyan-light": "#26464A",
  "--chakra-colors-bg-accent-secondary-green-light": "#33401F",
  "--chakra-colors-bg-accent-secondary-yellow-light": "#494531",
  "--chakra-colors-bg-accent-secondary-yellow-medium": "#E6DB74",
  "--chakra-colors-bg-accent-secondary-yellow-dark": "#F4E98A",
  "--chakra-colors-bg-accent-secondary-sand-light": "#3E3D32",
  "--chakra-colors-border": "#5B594A",
  "--chakra-colors-border-muted": "#49483E",
  "--chakra-colors-border-subtle": "#3E3D32",
  "--chakra-colors-border-inverted": "#CFCFC2",
  "--chakra-colors-border-accent-light": "#66D9EF",
  "--chakra-colors-border-accent": "#66D9EF",
  "--chakra-colors-blue-border": "#66D9EF",
  "--chakra-colors-blue-500": "#66D9EF",
  "--chakra-colors-blue-600": "#66D9EF",
  "--chakra-colors-blue-700": "#66D9EF",
  "--chakra-colors-fg-blue-dark": "#66D9EF",
  "--chakra-colors-foreground-accent-blue-dark": "#66D9EF",
  "--chakra-colors-orange-contrast": "#272822",
  "--chakra-colors-orange-fg": "#FD971F",
  "--chakra-colors-orange-subtle": "#493522",
  "--chakra-colors-orange-muted": "#5A3C20",
  "--chakra-colors-orange-emphasized": "#7A4D1D",
  "--chakra-colors-orange-solid": "#FD971F",
  "--chakra-colors-orange-focus-ring": "#FD971F",
  "--chakra-colors-orange-border": "#FD971F",
  "--chakra-colors-text-selectable-primary": "#272822",
  "--chakra-colors-vis-text-primary": "#F8F8F2",
  "--chakra-colors-vis-text-secondary": "#CFCFC2",
  "--chakra-colors-vis-grid": "#49483E",
  "--chakra-colors-vis-axis": "#A59F85",
  "--chakra-colors-vis-categorical-1": "#66D9EF",
  "--chakra-colors-vis-categorical-2": "#FD971F",
  "--chakra-colors-vis-categorical-3": "#AE81FF",
  "--chakra-colors-vis-categorical-4": "#F92672",
  "--chakra-colors-vis-categorical-5": "#E6DB74",
  "--chakra-colors-vis-categorical-6": "#A6E22E",
  "--chakra-colors-vis-categorical-7": "#75715E",
} satisfies ThemeCssVariables;

export const themePreferenceCssVariables = {
  "pstdio-light": {},
  "pstdio-dark": {},
  monokai: monokaiCssVariables,
} satisfies Record<ThemePreference, ThemeCssVariables>;

export const themePreferenceCssVariableNames = [
  ...new Set(Object.values(themePreferenceCssVariables).flatMap((variables) => Object.keys(variables))),
];
