name: Build Docker Images

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_images:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Build landing-page image
        run: docker build -t pstdio/landing-page:${IMAGE_TAG} -f clients/landing-page/Dockerfile .

      - name: Build api image
        run: docker build -t pstdio/api:${IMAGE_TAG} -f packages/pstdio-api/Dockerfile .
