name: License Compliance Check
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  merge_group:
  pull_request:
    branches:
      - "main"

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.13

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate license report
        run: bunx license-checker --production --csv > npm-license-checker.csv

      - name: Check license report
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          external: npm-license-checker.csv
          external-format: csv
          external-options: "{:skip-header true}"
          fail: WeakCopyleft,StrongCopyleft,NetworkCopyleft
          fails-only: true
          totals: true
          verbose: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo error
        if: failure()
        run: echo "::error::${{ steps.license_check_report.outputs.report }}"

      - name: Delete license report
        run: rm npm-license-checker.csv
