name: Delete Preview
on:
  pull_request:
    types: [closed]
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview app
        uses: digitalocean/app_action/delete@v2
        with:
          from_pr_preview: "true"
          ignore_not_found: "true"
          project_id: ee16f77b-a747-4eb7-af56-a21c8832f1ac
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
