name: Delete Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview app
        uses: digitalocean/app_action/delete@v2
        with:
          from_pr_preview: "true"
          ignore_not_found: "true"
          project_id: ${{ secrets.DIGITALOCEAN_PROJECT_ID }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
