export const dashboardCommandIds = {
  clearSelectedProject: "dashboard.clearSelectedProject",
  createProject: "dashboard.createProject",
  createSession: "dashboard.createSession",
  archiveWorkspace: "dashboard.archiveWorkspace",
  createWorkspace: "dashboard.createWorkspace",
  deleteWorkspace: "dashboard.deleteWorkspace",
  renameWorkspace: "dashboard.renameWorkspace",
  openCommandPalette: "dashboard.openCommandPalette",
  openCurrentWorkspace: "dashboard.openCurrentWorkspace",
  openDiscord: "dashboard.openDiscord",
  openDocs: "dashboard.openDocs",
  openFile: "dashboard.openFile",
  openFloatingSession: "dashboard.openFloatingSession",
  openProjects: "dashboard.openProjects",
  openSessions: "dashboard.openSessions",
  openShortcuts: "dashboard.openShortcuts",
  openWorkspaces: "dashboard.openWorkspaces",
  productInfo: "dashboard.productInfo",
  selectWorkspaceSidebarSession: "dashboard.selectWorkspaceSidebarSession",
} as const;
